server:
  port: 8070
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8088/eureka
  instance:
      leaseRenewalIntervalInSeconds: 30
      leaseExpirationDurationInSeconds: 60
      prefer-ip-address: true
      instance-id: ${spring.cloud.client.ipAddress}:${server.port}
spring:
  application:
    name: cloud-comsumer

######################################################################
# spring cloud feign retry config
# qust 2017-12-04
######################################################################
spring.cloud.loadbalancer.retry.enabled: true   # enable retry
hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 100000 # set hystrix timeout

client-service:
  ribbon:
    OkToRetryOnAllOperations: true
    MaxAutoRetriesNextServer: 2
    MaxAutoRetries: 1
    ConnectTimeout: 250
    ReadTimeout: 1000
