server:
  port: 8070
eureka:
  client:
    service-url:
      defaultZone: http://192.168.2.107:8088/eureka
  instance:
      leaseRenewalIntervalInSeconds: 30
      leaseExpirationDurationInSeconds: 60
      prefer-ip-address: true
      instance-id: ${spring.cloud.client.ipAddress}:${server.port}
spring:
  application:
    name: cloud-comsumer
  redis:
    cluster:
      nodes: 192.168.2.17:50611,192.168.2.18:56020
    password: foo123
    pool:
      max-active: 800
      max-idle: 100
      max-wait: 5000
      min-idle: 30

######################################################################
# spring cloud feign retry config
# qust 2017-12-04
######################################################################
spring.cloud.loadbalancer.retry.enabled: true   # enable retry
hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 100000 # set hystrix timeout

client-service:
  ribbon:
    OkToRetryOnAllOperations: true
    MaxAutoRetriesNextServer: 2
    MaxAutoRetries: 1
    ConnectTimeout: 250
    ReadTimeout: 1000


#/configurations/microserver/commonconfig/spring/redis/pool=max-active=800
#/configurations/microserver/commonconfig/spring/redis/pool=max-idle=100
#/configurations/microserver/commonconfig/spring/redis/pool=max-wait=5000
#/configurations/microserver/commonconfig/spring/redis/pool=min-idle=30
#/configurations/microserver/commonconfig/spring/redis=database=3
#/configurations/microserver/commonconfig/spring/redis=host=192.168.2.200
#/configurations/microserver/commonconfig/spring/redis=port=6379